title = "Default configuration file"

[flavors]
  [flavors.default]
    # This section is here to override the default builtins of ceph-nano
    # memory_size = "512MB"
    # use_default = true
    # cpu_count = 1
  [flavors.mycustom]
    # memory_size = "10GB"

[images]
  [images.default]
  # This section is here to override the default builtins of ceph-nano
  # image_name="registry/username/image:tag"
  [images.mycustom]
  # image_name="myregistry/myusername/myimage:mytag"
